### ISSUE TITLE
Nieuw project voor Extension rond plaatsnamen Oekraïne?

### ISSUE THREAD

**Issue by peSHIr** [rutgersmit/pauperkabouter#6]
Analoog aan code Pauperkabouter, maar dan een aantal zoek/vervang-items die allemaal worden uitgevoerd, met een blauw/gele vlag als icoontje? Zie [Twitter-thread] (https://twitter.com/DieTukkerfries/status/1498326397902798857)

**Comment by rutgersmit** [comment]
Zou technisch wel kunnen, maar dan kun je beter een bestaande extension zoals [Word Replacer](https://chrome.google.com/webstore/detail/word-replacer-ii/djakfbefalbkkdgnhkkdiihelkjdpbfh?hl=en) gebruiken. Lil Kleine vervangen had natuurlijk ook prima met deze gekund, maar daar gaat het natuurlijk niet om ;)
